### PROYECTO MODULO 4 ##

**1. DATASET PRINCIPAL : Worldwide Travel Cities**
(560 filas × 19 columnas)

Para identificar: 
- city
- country
- region
- latitude
- longitude

Para perfil turistico:
- budget_level
- ideal_duration (pendiente)

Para ratings:
- culture
- adventure
- nature
- beaches
- nightlife
- cuisine
- wellness
- urban
- seclusion
- avg_temp_monthly (pendeinte)

**2. DATASET UNESCO ccreative cities:**
(402 filas × 32 columnas) nos interesansolo: 

- city
- unesco_category (gastronomy, music, design, literature)
- fecha


**3. DATASET World Heritage:**
(1248 filas × 49 columnas)

Nos servira para calcular numero de patrimonios unesco por pais.

- city
- Country (si existe)
- category (cultural, natural, mixed)
- name_en (nombre del patrimonio)

1. Primer paso: verificar datos dataset principal, worldwide travel cities y eliminar columnas.

In [ ]:
import pandas as pd
import numpy as np #Esto es para trabajar con arrays y operaciones matemáticas
import warnings #Esto sirve para manejar las advertencias que puedan surgir durante la ejecución del código
warnings.filterwarnings('ignore')

# Mostrar todas las columnas sin truncar
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 60)

print("✅ Librerías cargadas correctamente")

travel = pd.read_csv('worldwide_travel_cities.csv')
print(f"El número de filas y columnas es: {travel.shape[0]} filas y {travel.shape[1]} columnas")

✅ Librerías cargadas correctamente
El número de filas y columnas es: 560 filas y 19 columnas

In [12]:
df = travel.copy()

In [16]:
def eda_basico(df):
    print("🔍 Primeras filas del DataFrame:")
    display(df.head())

    print("🔍 Últimas filas del DataFrame:")
    display(df.tail())

    print("📌 Filas Aleatorias:")
    display(df.sample(n=5))

    print("📐 Dimensiones:")
    print(f"{df.shape[0]} filas y {df.shape[1]} columnas\n")

    print("🧠 Información general:")
    display(df.info())

    print("📊 Tipos de datos por columna:")
    display(df.dtypes.rename("Tipo").to_frame())

    print("📉 Descripción de columnas numéricas:")
    display(df.describe().T)

    print("🔤 Descripción de columnas categóricas:")
    display(df.describe(include=["O"]))

    print("🚫 Valores nulos por columna:")
    nulos = df.isnull().sum()
    nulos = nulos[nulos > 0].sort_values(ascending=False)
    if len(nulos) > 0:
        display(pd.DataFrame({
            "Nulos": nulos,
            "Porcentaje (%)": (nulos / len(df) * 100).round(2)
        }))
    else:
        print("No hay valores nulos.\n")

    print("🗑️ Columnas constantes:")
    constantes = [col for col in df.columns if df[col].nunique() == 1]
    if constantes:
        display(pd.DataFrame({
            "Columna": constantes,
            "Valor único": [df[col].unique()[0] for col in constantes],
            "Acción": ["Eliminar en Fase 2"] * len(constantes)
        }))
    else:
        print("No hay columnas constantes.\n")

    print("📎 Filas duplicadas:")
    dup_count = df.duplicated().sum()
    print(f"Duplicadas: {dup_count}")
    if dup_count > 0:
        print("Ejemplo de duplicados:")
        display(df[df.duplicated()].head())
    else:
        print("No hay filas duplicadas.\n")

In [17]:
eda_basico(df)

🔍 Primeras filas del DataFrame:

,id,city,country,region,short_description,latitude,longitude,avg_temp_monthly,ideal_durations,budget_level,culture,adventure,nature,beaches,nightlife,cuisine,wellness,urban,seclusion
0,c54acf38-3029-496b-8c7a-8343ad82785c,Milan,Italy,europe,"Chic streets lined with fashion boutiques, his...",45.464194,9.189635,"{""1"":{""avg"":3.7,""max"":7.8,""min"":0.4},""2"":{""avg...","[""Short trip"",""One week""]",Luxury,5,2,2,1,4,5,3,5,2
1,0bd12654-ed64-424e-a044-7bc574bcf078,Yasawa Islands,Fiji,oceania,"Crystal-clear waters, secluded beaches, and vi...",-17.290947,177.125786,"{""1"":{""avg"":28,""max"":30.8,""min"":25.8},""2"":{""av...","[""Long trip"",""One week""]",Luxury,2,4,5,5,2,3,4,1,5
2,73036cda-9134-46fc-a2c6-807782d59dfb,Whistler,Canada,north_america,Snow-capped peaks and lush forests create a se...,50.117190,-122.954302,"{""1"":{""avg"":-2.5,""max"":0.4,""min"":-5.5},""2"":{""a...","[""Short trip"",""Weekend"",""One week""]",Luxury,3,5,5,2,3,3,4,2,4
3,3872c9c0-6b6e-49e1-9743-f46bfe591b86,Guanajuato,Mexico,north_america,Winding cobblestone streets and colorful facad...,20.987700,-101.000000,"{""1"":{""avg"":15.5,""max"":22.8,""min"":8.7},""2"":{""a...","[""Weekend"",""One week"",""Short trip""]",Mid-range,5,3,3,1,3,4,3,4,2
4,e1ebc1b6-8798-422d-847a-22016faff3fd,Surabaya,Indonesia,asia,Bustling streets filled with the aroma of loca...,-7.245972,112.737827,"{""1"":{""avg"":28.1,""max"":32.5,""min"":25.5},""2"":{""...","[""Short trip"",""Weekend""]",Budget,4,3,3,2,3,4,3,4,2

🔍 Últimas filas del DataFrame:

,id,city,country,region,short_description,latitude,longitude,avg_temp_monthly,ideal_durations,budget_level,culture,adventure,nature,beaches,nightlife,cuisine,wellness,urban,seclusion
555,778d28df-a4fa-4328-896e-4a9f80216fda,Maun,Botswana,africa,"A gateway to the Okavango Delta, offering a se...",-19.986095,23.422435,"{""1"":{""avg"":26.6,""max"":32,""min"":21.2},""2"":{""av...","[""One week"",""Short trip""]",Mid-range,3,5,5,1,2,3,3,2,4
556,44fb18eb-2641-46ab-b3fa-df6870ba3c74,Gothenburg,Sweden,europe,"A charming city with picturesque canals, lush ...",57.707233,11.967017,"{""1"":{""avg"":1.4,""max"":3.2,""min"":-1.2},""2"":{""av...","[""Weekend"",""One week"",""Short trip""]",Mid-range,4,3,4,3,3,4,3,4,3
557,8c8c7203-2a45-44ba-9fb2-b5158104375e,Manchester,United Kingdom,europe,"Industrial heritage meets modern creativity, w...",53.479489,-2.245115,"{""1"":{""avg"":4.7,""max"":7.1,""min"":2},""2"":{""avg"":...","[""Weekend"",""One week"",""Short trip""]",Mid-range,4,2,2,1,4,4,3,4,2
558,ba72b976-10f9-4415-a818-32cf17d8e649,Copenhagen,Denmark,europe,"Charming canals, vibrant neighborhoods, and a ...",55.686724,12.570072,"{""1"":{""avg"":2.6,""max"":4.2,""min"":0.6},""2"":{""avg...","[""One week"",""Short trip"",""Weekend""]",Mid-range,5,2,3,2,4,4,3,5,2
559,62caf451-c399-4d64-a770-1efd93a603ef,Sucre,Bolivia,south_america,"Whitewashed colonial buildings, vibrant plazas...",-19.047725,-65.259431,"{""1"":{""avg"":15.4,""max"":19.8,""min"":10.2},""2"":{""...","[""Short trip"",""Weekend"",""One week""]",Budget,4,3,3,1,2,3,2,2,4

📌 Filas Aleatorias:

,id,city,country,region,short_description,latitude,longitude,avg_temp_monthly,ideal_durations,budget_level,culture,adventure,nature,beaches,nightlife,cuisine,wellness,urban,seclusion
18,79a47311-1ffb-44d1-bd87-a1a9fb190f40,Chicago,United States,north_america,"Dynamic streets filled with diverse food, vibr...",41.875562,-87.624421,"{""1"":{""avg"":-2.5,""max"":0.7,""min"":-6.1},""2"":{""a...","[""One week"",""Short trip""]",Luxury,5,3,3,2,5,5,3,5,2
163,1c1ede32-515d-4a46-8019-15e3196afd18,Castries,Saint Lucia,north_america,"Colorful markets, ocean breezes, and lively st...",13.909044,-60.977924,"{""1"":{""avg"":25.5,""max"":28.5,""min"":23.1},""2"":{""...","[""Weekend"",""One week"",""Short trip""]",Mid-range,3,4,5,5,3,4,4,3,4
274,44270077-ff2f-4123-96b9-7158aaff58a9,Luxor,Egypt,africa,Sun-drenched landscapes and ancient temples cr...,25.702096,32.647186,"{""1"":{""avg"":15.4,""max"":22.5,""min"":8.5},""2"":{""a...","[""Short trip"",""One week""]",Budget,5,3,3,1,2,4,2,3,3
139,34daf415-739f-45d7-a127-f47f0dcf63f9,Arequipa,Peru,south_america,Charming colonial architecture and vibrant pla...,-16.398867,-71.536961,"{""1"":{""avg"":15.6,""max"":20,""min"":10.9},""2"":{""av...","[""Weekend"",""One week"",""Short trip""]",Budget,4,3,4,1,3,4,3,3,3
193,4959b5b0-bc55-450f-a2c5-9076efac17a7,Tunis,Tunisia,africa,Wander through bustling souks and historic med...,36.800207,10.185776,"{""1"":{""avg"":12.4,""max"":16.7,""min"":8.6},""2"":{""a...","[""Weekend"",""Short trip""]",Budget,4,3,3,3,3,4,3,3,2

📐 Dimensiones:
560 filas y 19 columnas

🧠 Información general:
<class 'pandas.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 560 non-null    str
 1   city               560 non-null    str
 2   country            560 non-null    str
 3   region             560 non-null    str
 4   short_description  560 non-null    str
 5   latitude           560 non-null    float64
 6   longitude          560 non-null    float64
 7   avg_temp_monthly   560 non-null    str
 8   ideal_durations    560 non-null    str
 9   budget_level       560 non-null    str
 10  culture            560 non-null    int64
 11  adventure          560 non-null    int64
 12  nature             560 non-null    int64
 13  beaches            560 non-null    int64
 14  nightlife          560 non-null    int64
 15  cuisine            560 non-null    int64
 16  wellness           560 non-null    int64
 17  urban              560 non-null    int64
 18  seclusion          560 non-null    int64
dtypes: float64(2), int64(9), str(8)
memory usage: 83.3 KB

None

📊 Tipos de datos por columna:

                      Tipo
id                     str
city                   str
country                str
region                 str
short_description      str
latitude           float64
longitude          float64
avg_temp_monthly       str
ideal_durations        str
budget_level           str
culture              int64
adventure            int64
nature               int64
beaches              int64
nightlife            int64
cuisine              int64
wellness             int64
urban                int64
seclusion            int64

📉 Descripción de columnas numéricas:

,count,mean,std,min,25%,50%,75%,max
latitude,560.0,22.502186,27.980022,-54.807306,5.268054,31.793618,43.673199,78.719852
longitude,560.0,7.914665,78.813803,-175.201808,-64.439118,10.711854,50.020162,179.332896
culture,560.0,3.850000,0.812910,2.000000,3.000000,4.000000,4.000000,5.000000
adventure,560.0,3.178571,0.798190,2.000000,3.000000,3.000000,4.000000,5.000000
nature,560.0,3.728571,0.903920,2.000000,3.000000,4.000000,4.000000,5.000000
beaches,560.0,2.380357,1.435547,1.000000,1.000000,2.000000,3.000000,5.000000
nightlife,560.0,3.019643,0.921599,1.000000,2.000000,3.000000,4.000000,5.000000
cuisine,560.0,3.792857,0.679329,2.000000,3.000000,4.000000,4.000000,5.000000
wellness,560.0,3.073214,0.592134,2.000000,3.000000,3.000000,3.000000,5.000000
urban,560.0,3.146429,1.018604,1.000000,2.000000,3.000000,4.000000,5.000000
seclusion,560.0,3.028571,0.989699,1.000000,2.000000,3.000000,4.000000,5.000000

🔤 Descripción de columnas categóricas:

,id,city,country,region,short_description,avg_temp_monthly,ideal_durations,budget_level
count,560,560,560,560,560,560,560,560
unique,560,559,167,7,560,545,21,3
top,c54acf38-3029-496b-8c7a-8343ad82785c,Granada,United States,europe,"Chic streets lined with fashion boutiques, his...","{""1"":{""avg"":28.5,""max"":32.5,""min"":25.2},""2"":{""...","[""Short trip"",""Weekend"",""One week""]",Mid-range
freq,1,2,50,177,1,3,120,339

🚫 Valores nulos por columna:
No hay valores nulos.

🗑️ Columnas constantes:
No hay columnas constantes.

📎 Filas duplicadas:
Duplicadas: 0
No hay filas duplicadas.

In [18]:
df.drop(columns=["id", "short_description"], inplace=True)
df.columns

Index(['city', 'country', 'region', 'latitude', 'longitude',
       'avg_temp_monthly', 'ideal_durations', 'budget_level', 'culture',
       'adventure', 'nature', 'beaches', 'nightlife', 'cuisine', 'wellness',
       'urban', 'seclusion'],
      dtype='str')

2. Segundo paso: verificar datos dataset UNESCO creative cities y eliminar columnas.

( - country, - unesco_category (gastronomy, music, design, literature), - fecha)

In [47]:
unesco = pd.read_csv("unesco_creative_cities.csv")
print(f"El número de filas y columnas es: {travel.shape[0]} filas y {travel.shape[1]} columnas")

El número de filas y columnas es: 560 filas y 19 columnas

In [48]:
df2 = unesco.copy()

In [40]:
def eda_basico(df2):
    print("🔍 Primeras filas del DataFrame:")
    display(df2.head())

    print("🔍 Últimas filas del DataFrame:")
    display(df2.tail())

    print("📌 Filas Aleatorias:")
    display(df2.sample(n=5))

    print("📐 Dimensiones:")
    print(f"{df2.shape[0]} filas y {df2.shape[1]} columnas\n")

    print("🧠 Información general:")
    display(df2.info())

    print("📊 Tipos de datos por columna:")
    display(df2.dtypes.rename("Tipo").to_frame())

    print("📉 Descripción de columnas numéricas:")
    display(df2.describe().T)

    print("🔤 Descripción de columnas categóricas:")
    display(df2.describe(include=["O"]))

    print("🚫 Valores nulos por columna:")
    nulos = df2.isnull().sum()
    nulos = nulos[nulos > 0].sort_values(ascending=False)
    if len(nulos) > 0:
        display(pd.DataFrame({
            "Nulos": nulos,
            "Porcentaje (%)": (nulos / len(df2) * 100).round(2)
        }))
    else:
        print("No hay valores nulos.\n")

    print("🗑️ Columnas constantes:")
    constantes = [col for col in df2.columns if df2[col].nunique() == 1]
    if constantes:
        display(pd.DataFrame({
            "Columna": constantes,
            "Valor único": [df2[col].unique()[0] for col in constantes],
            "Acción": ["Eliminar en Fase 2"] * len(constantes)
        }))
    else:
        print("No hay columnas constantes.\n")

    print("📎 Filas duplicadas:")
    dup_count = df2.duplicated().sum()
    print(f"Duplicadas: {dup_count}")
    if dup_count > 0:
        print("Ejemplo de duplicados:")
        display(df2[df2.duplicated()].head())
    else:
        print("No hay filas duplicadas.\n")

In [49]:
eda_basico(df2)

🔍 Primeras filas del DataFrame:

,ID,UUID,Términos,Título EN,Título ES,Título FR,Título ZH,Fecha,Descripción EN,Descripción ES,Descripción FR,Descripción ZH,Contact EN,Contacto ES,Contacto Fr,Descripción ZH.1,Creado en,Actualizado en,Título AR,Título RU,Descripción AR,Descripción RU,Descripción AR.1,Descripción RU.1,documentId,publishedAt,related_links,main_image,monitoring_report,postal_address,strapi_stage,strapi_assignee
0,1455,93fa71e7-ad6f-41e1-8992-7402a3458000,Design,Detroit,Detroit,Détroit,底特律,2015,"<p>Detroit, a metropolis of more than 6 millio...",<p><em>Esta página está disponible por el mome...,"<p>Détroit, métropole de plus de 6 millions d’...",<p>底特律是一个拥有600多万居民的大都市，被视为密歇根州（美利坚合众国）工业设计的中心和...,"{""address"":"""",""address_2"":"""",""city"":""Detroit"",...","{""address"":"""",""address_2"":"""",""city"":""Detroit"",...","{""address"":"""",""address_2"":"""",""city"":""D\u00e9tr...","{""address"":"""",""address_2"":"""",""city"":""\u5e95\u7...",2024-01-18T14:25:01+01:00,2026-03-02T08:30:19+01:00,NaN,NaN,NaN,NaN,NaN,NaN,yzyzyg5ot2olavnamrvjum5k,2026-03-02T08:30:19+01:00,[],"{'id': 7874086, 'title': '', 'copyright': '', ...",[],"[{'id': 20670495, 'street_address': None, 'loc...",NaN,NaN
1,1457,8a2def46-5900-4e00-b4ae-3bfe18bc012f,Literature,Manchester,Manchester,Manchester,Manchester,2017,"<p>Manchester has a proud history in music, sc...",<p><em>Esta página está disponible por el mome...,<p>Manchester est fière du rôle qu’elle a joué...,<p><em>This page is only available in English ...,"{""address"":"""",""address_2"":"""",""city"":""Mancheste...","{""address"":"""",""address_2"":"""",""city"":""Mancheste...","{""address"":"""",""address_2"":"""",""city"":""Mancheste...","{""address"":"""",""address_2"":"""",""city"":""Mancheste...",2024-01-18T14:25:01+01:00,2026-03-02T08:30:24+01:00,NaN,NaN,NaN,NaN,NaN,NaN,wc5nl62oysyemj32rfjlouav,2026-03-02T08:30:24+01:00,[],"{'id': 7874118, 'title': '', 'copyright': '', ...",[],"[{'id': 20670527, 'street_address': None, 'loc...",NaN,NaN
2,1458,ecc58c4b-92c9-477c-8882-12e4bcc30c8c,Music,Praia,Praia,Praia,Praia,2017,"<p>Praia (pop. 155,252), the capital of Cabo V...",<p><em>Esta página está disponible por el mome...,"<p>Situé sur l´île de Santiago, Praia (pop. 15...",<p><em>This page is only available in English ...,"{""address"":"""",""address_2"":"""",""city"":""Praia"",""c...","{""address"":"""",""address_2"":"""",""city"":""Praia"",""c...","{""address"":"""",""address_2"":"""",""city"":""Praia"",""c...","{""address"":"""",""address_2"":"""",""city"":""Praia"",""c...",2024-01-18T14:25:01+01:00,2026-03-02T08:30:26+01:00,NaN,NaN,NaN,NaN,NaN,NaN,fb3odllwya52lfoxvn8x65bv,2026-03-02T08:30:26+01:00,[],"{'id': 7874134, 'title': '', 'copyright': '', ...",[],"[{'id': 20670543, 'street_address': None, 'loc...",NaN,NaN
3,1462,73c12416-16d8-4c97-b753-af256131cc8d,Design,San José,NaN,San José,NaN,2019,"<p>With its 4,947,490 inhabitants, San José, t...",NaN,"<p>Avec ses 4 947 490 habitants, San José, cap...",NaN,"{""address"":"""",""address_2"":"""",""city"":""San Jos\u...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":""San Jos\u...",NaN,2024-01-18T14:25:02+01:00,2026-03-02T08:30:34+01:00,NaN,NaN,NaN,NaN,NaN,NaN,hlga86exykiz4dhndjjo6fck,2026-03-02T08:30:34+01:00,[],"{'id': 7874198, 'title': '', 'copyright': '', ...",[],"[{'id': 20670607, 'street_address': None, 'loc...",NaN,NaN
4,1463,54659f38-662b-485e-9091-3d1ad2e1cd16,Film,Wellington,NaN,Wellington,NaN,2019,"<p>Wellington is New Zealand’s creative heart,...",NaN,<p>Wellington est le centre créatif de la Nouv...,NaN,"{""address"":"""",""address_2"":"""",""city"":""Wellingto...",NaN,"{""address"":"""",""address_2"":"""",""city"":""Wellingto...",NaN,2024-01-18T14:25:02+01:00,2026-03-02T08:30:36+01:00,NaN,NaN,NaN,NaN,NaN,NaN,bvlw8zoku6efjpojfwwfxj6v,2026-03-02T08:30:36+01:00,[],"{'id': 7874214, 'title': '', 'copyright': '', ...",[],"[{'id': 20670623, 'street_address': None, 'loc...",NaN,NaN

🔍 Últimas filas del DataFrame:

,ID,UUID,Términos,Título EN,Título ES,Título FR,Título ZH,Fecha,Descripción EN,Descripción ES,Descripción FR,Descripción ZH,Contact EN,Contacto ES,Contacto Fr,Descripción ZH.1,Creado en,Actualizado en,Título AR,Título RU,Descripción AR,Descripción RU,Descripción AR.1,Descripción RU.1,documentId,publishedAt,related_links,main_image,monitoring_report,postal_address,strapi_stage,strapi_assignee
397,1846,9736b5cf-0223-47bd-8b96-d6303aa65828,Crafts and Folk Art,Sarchí,NaN,Sarchí,NaN,2025,<p><span><strong>About the Creative City:&nbsp...,NaN,<p><span><strong>À propos de la Ville créative...,NaN,"{""name"":"""",""company"":"""",""email"":""ciudad_creati...","{""name"":"""",""company"":"""",""email"":""ciudad_creati...","{""name"":"""",""company"":"""",""email"":""ciudad_creati...",NaN,2026-03-23T17:46:49+01:00,2026-03-24T10:41:22+01:00,NaN,NaN,NaN,NaN,NaN,NaN,tflhib2bvoqukevlghm5549l,2026-03-24T10:41:22+01:00,[],"{'id': 9793261, 'title': '', 'copyright': 'Car...",[],"[{'id': 20674523, 'street_address': None, 'loc...",NaN,NaN
398,1855,a5e6c358-ead3-4dfe-980c-d6d8449edd28,Music,Wuxi,NaN,Wuxi,NaN,2025,<p><strong>About the Creative City:</strong><b...,NaN,<p><strong>À propos de la Ville créative :</st...,NaN,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...",NaN,2026-04-30T21:45:17+02:00,2026-04-30T21:45:17+02:00,NaN,NaN,NaN,NaN,NaN,NaN,evj4vqdcwx4sz2uujji94flj,2026-04-30T21:45:17+02:00,[],"{'id': 11002180, 'title': 'Wuxi ', 'copyright'...",[],"[{'id': 20696185, 'street_address': None, 'loc...",NaN,NaN
399,1856,2828fc45-4f49-4150-a96f-796031e3875f,Music,Kisumu,NaN,Kisumu,NaN,2025,<p><strong>About the Creative City:</strong><b...,NaN,<p><strong>À propos de la Ville créative :</st...,NaN,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...",NaN,2026-04-30T21:45:20+02:00,2026-04-30T21:45:20+02:00,NaN,NaN,NaN,NaN,NaN,NaN,makwpmwi16935tb8ipfm7ro0,2026-04-30T21:45:20+02:00,[],"{'id': 11002181, 'title': 'Kisumu', 'copyright...",[],"[{'id': 20696186, 'street_address': None, 'loc...",NaN,NaN
400,1857,c50c18bb-98e2-4675-bcd7-c07bdc1b9063,Music,New Orleans,NaN,La Nouvelle-Orléans,NaN,2025,<p><strong>About the Creative City:</strong><b...,NaN,<p><strong>À propos de la Ville créative :</st...,NaN,NaN,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...",NaN,2026-04-30T21:45:24+02:00,2026-04-30T21:45:24+02:00,NaN,NaN,NaN,NaN,NaN,NaN,j11idqn0hinn9lrwoctsfbsh,2026-04-30T21:45:24+02:00,[],"{'id': 11002183, 'title': 'New Orleans ', 'cop...",[],"[{'id': 20696188, 'street_address': None, 'loc...",NaN,NaN
401,1859,657d5a5b-4b90-4b60-be11-38538a1d4b99,Music,Lalitpur,NaN,Lalitpur,NaN,2025,<p><strong>About the Creative City:</strong><b...,NaN,<p><strong>À propos de la Ville créative :</st...,NaN,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...",NaN,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...",NaN,2026-04-30T21:45:30+02:00,2026-04-30T21:45:30+02:00,NaN,NaN,NaN,NaN,NaN,NaN,egbd6zv5e7f5eprg09s19kx1,2026-04-30T21:45:30+02:00,[],"{'id': 11002187, 'title': 'Lalitpur', 'copyrig...",[],"[{'id': 20696192, 'street_address': None, 'loc...",NaN,NaN

📌 Filas Aleatorias:

,ID,UUID,Términos,Título EN,Título ES,Título FR,Título ZH,Fecha,Descripción EN,Descripción ES,Descripción FR,Descripción ZH,Contact EN,Contacto ES,Contacto Fr,Descripción ZH.1,Creado en,Actualizado en,Título AR,Título RU,Descripción AR,Descripción RU,Descripción AR.1,Descripción RU.1,documentId,publishedAt,related_links,main_image,monitoring_report,postal_address,strapi_stage,strapi_assignee
66,1658,c1a06eb4-0ddf-43eb-bb02-a677b8703dcc,Literature,Bucheon,Bucheon,Bucheon,Bucheon,2017,"<p>Bucheon (pop. 870,000) owes its vibrant lit...",<p><em>Esta página está disponible por el mome...,<p>Bucheon (pop. 870 000) doit son patrimoine ...,<p><em>This page is only available in English ...,"{""address"":"""",""address_2"":"""",""city"":""Bucheon"",...","{""address"":"""",""address_2"":"""",""city"":""Bucheon"",...","{""address"":"""",""address_2"":"""",""city"":""Bucheon"",...","{""address"":"""",""address_2"":"""",""city"":""Bucheon"",...",2024-01-18T14:25:28+01:00,2026-03-02T08:30:21+01:00,NaN,NaN,NaN,NaN,NaN,NaN,qml3o0ltexjzewvirnq6k51p,2026-03-02T08:30:21+01:00,[],"{'id': 7874097, 'title': '', 'copyright': '', ...",[],"[{'id': 20670506, 'street_address': None, 'loc...",NaN,NaN
296,1556,76f6f70d-dab9-43e8-8a74-bb5a4c739121,Music,Metz,NaN,Metz,NaN,2019,"<p>Metz, located near Luxembourg, Belgium and ...",NaN,"<p>Metz, située à proximité du Luxembourg, de ...",NaN,"{""address"":"""",""address_2"":"""",""city"":""Metz"",""co...",NaN,"{""address"":"""",""address_2"":"""",""city"":""Metz"",""co...",NaN,2024-01-18T14:25:15+01:00,2026-03-02T08:30:33+01:00,NaN,NaN,NaN,NaN,NaN,NaN,yqb7iz5366y4cmtxrn1zwg1x,2026-03-02T08:30:33+01:00,[],"{'id': 7874187, 'title': '', 'copyright': '', ...",[],"[{'id': 20670596, 'street_address': None, 'loc...",NaN,NaN
248,1822,3bd6c4ca-be19-439b-971d-3d5de48a397c,Literature,Lund,NaN,Lund,NaN,2025,"<p class=""text-align-justify""><a target=""_blan...",NaN,"<p class=""text-align-justify""><a target=""_blan...",NaN,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...",NaN,2026-02-18T14:00:13+01:00,2026-03-02T08:30:52+01:00,NaN,NaN,NaN,NaN,NaN,NaN,cbs2p4i09iaeg9wxhymlxrnm,2026-03-02T08:30:52+01:00,[],"{'id': 7874329, 'title': 'Lund ', 'copyright':...",[],"[{'id': 20670738, 'street_address': None, 'loc...",NaN,NaN
69,1666,8682e52f-8db0-4165-9ae4-b67ab7b4a8fa,Media Arts,Campina Grande,NaN,Campina Grande,NaN,2021,<p>The Brazilian city of Campina Grande has a ...,NaN,<p>La ville brésilienne de Campina Grande est ...,NaN,"{""address"":"""",""address_2"":"""",""city"":""Campina G...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":""Campina G...",NaN,2024-01-18T14:25:29+01:00,2026-03-02T08:30:38+01:00,NaN,NaN,NaN,NaN,NaN,NaN,mryitfsy8xai67pswyx13t8w,2026-03-02T08:30:38+01:00,[],"{'id': 7874225, 'title': '', 'copyright': '', ...",[],"[{'id': 20670634, 'street_address': None, 'loc...",NaN,NaN
118,1847,102c232c-89ec-449d-b76d-5beab8ed44ca,Crafts and Folk Art,Nan,NaN,Nan,NaN,2025,<p><span><strong>About the Creative City:&nbsp...,NaN,<p><span><strong>À propos de la Ville créative...,NaN,"{""name"":"""",""company"":"""",""email"":""NanCreativeCi...","{""name"":"""",""company"":"""",""email"":""NanCreativeCi...","{""name"":"""",""company"":"""",""email"":""NanCreativeCi...",NaN,2026-03-23T17:46:53+01:00,2026-03-24T10:45:10+01:00,NaN,NaN,NaN,NaN,NaN,NaN,oivrwxgquz97irb0xhw0s3m2,2026-03-24T10:45:10+01:00,[],"{'id': 9793265, 'title': '', 'copyright': 'Pha...",[],"[{'id': 20674526, 'street_address': None, 'loc...",NaN,NaN

📐 Dimensiones:
402 filas y 32 columnas

🧠 Información general:
<class 'pandas.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 402 non-null    int64
 1   UUID               402 non-null    str
 2   Términos           402 non-null    str
 3   Título EN          402 non-null    str
 4   Título ES          180 non-null    str
 5   Título FR          402 non-null    str
 6   Título ZH          180 non-null    str
 7   Fecha              402 non-null    int64
 8   Descripción EN     402 non-null    str
 9   Descripción ES     180 non-null    str
 10  Descripción FR     402 non-null    str
 11  Descripción ZH     178 non-null    str
 12  Contact EN         393 non-null    str
 13  Contacto ES        276 non-null    str
 14  Contacto Fr        393 non-null    str
 15  Descripción ZH.1   185 non-null    str
 16  Creado en          402 non-null    str
 17  Actualizado en     402 non-null    str
 18  Título AR          0 non-null      float64
 19  Título RU          0 non-null      float64
 20  Descripción AR     0 non-null      float64
 21  Descripción RU     0 non-null      float64
 22  Descripción AR.1   10 non-null     str
 23  Descripción RU.1   6 non-null      str
 24  documentId         402 non-null    str
 25  publishedAt        402 non-null    str
 26  related_links      402 non-null    str
 27  main_image         402 non-null    str
 28  monitoring_report  402 non-null    str
 29  postal_address     402 non-null    str
 30  strapi_stage       0 non-null      float64
 31  strapi_assignee    0 non-null      float64
dtypes: float64(6), int64(2), str(24)
memory usage: 100.6 KB

None

📊 Tipos de datos por columna:

                      Tipo
ID                   int64
UUID                   str
Términos               str
Título EN              str
Título ES              str
Título FR              str
Título ZH              str
Fecha                int64
Descripción EN         str
Descripción ES         str
Descripción FR         str
Descripción ZH         str
Contact EN             str
Contacto ES            str
Contacto Fr            str
Descripción ZH.1       str
Creado en              str
Actualizado en         str
Título AR          float64
Título RU          float64
Descripción AR     float64
Descripción RU     float64
Descripción AR.1       str
Descripción RU.1       str
documentId             str
publishedAt            str
related_links          str
main_image             str
monitoring_report      str
postal_address         str
strapi_stage       float64
strapi_assignee    float64

📉 Descripción de columnas numéricas:

,count,mean,std,min,25%,50%,75%,max
ID,402.0,1652.131841,119.976245,1448.0,1549.25,1649.5,1756.75,1861.0
Fecha,402.0,2018.455224,4.650287,2004.0,2015.00,2019.0,2023.00,2025.0
Título AR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Título RU,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Descripción AR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Descripción RU,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
strapi_stage,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
strapi_assignee,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

🔤 Descripción de columnas categóricas:

,UUID,Términos,Título EN,Título ES,Título FR,Título ZH,Descripción EN,Descripción ES,Descripción FR,Descripción ZH,Contact EN,Contacto ES,Contacto Fr,Descripción ZH.1,Creado en,Actualizado en,Descripción AR.1,Descripción RU.1,documentId,publishedAt,related_links,main_image,monitoring_report,postal_address
count,402,402,402,180,402,180,402,180,402,178,393,276,393,185,402,402,10,6,402,402,402,402,402,402
unique,402,7,401,180,402,180,402,7,402,123,393,271,393,181,147,89,6,2,402,89,3,402,1,402
top,93fa71e7-ad6f-41e1-8992-7402a3458000,Music,Granada,Detroit,Détroit,底特律,"<p>Detroit, a metropolis of more than 6 millio...",<p><em>Esta página está disponible por el mome...,"<p>Détroit, métropole de plus de 6 millions d’...",<p><em>This page is only available in English ...,"{""address"":"""",""address_2"":"""",""city"":""Detroit"",...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":""D\u00e9tr...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...",2024-01-18T14:25:18+01:00,2026-03-02T08:30:43+01:00,"{""address"":"""",""address_2"":"""",""city"":"""",""compan...","{""address"":"""",""address_2"":"""",""city"":"""",""compan...",yzyzyg5ot2olavnamrvjum5k,2026-03-02T08:30:34+01:00,[],"{'id': 7874086, 'title': '', 'copyright': '', ...",[],"[{'id': 20670495, 'street_address': None, 'loc..."
freq,1,83,2,1,1,1,1,76,1,35,1,5,1,5,9,9,5,5,1,8,400,1,402,1

🚫 Valores nulos por columna:

                  Nulos  Porcentaje (%)
Descripción RU      402          100.00
Descripción AR      402          100.00
strapi_stage        402          100.00
strapi_assignee     402          100.00
Título RU           402          100.00
Título AR           402          100.00
Descripción RU.1    396           98.51
Descripción AR.1    392           97.51
Descripción ZH      224           55.72
Descripción ES      222           55.22
Título ES           222           55.22
Título ZH           222           55.22
Descripción ZH.1    217           53.98
Contacto ES         126           31.34
Contacto Fr           9            2.24
Contact EN            9            2.24

🗑️ Columnas constantes:

             Columna Valor único              Acción
0  monitoring_report          []  Eliminar en Fase 2

📎 Filas duplicadas:
Duplicadas: 0
No hay filas duplicadas.

In [51]:
df2 = df2[["Título EN", "Términos", "Fecha"]]

In [52]:
df2.rename(columns={"Título EN": "city", "Términos": "unesco_category", "Fecha": "unesco_year"}, inplace=True)

In [53]:
df2.head()

         city unesco_category  unesco_year
0     Detroit          Design         2015
1  Manchester      Literature         2017
2       Praia           Music         2017
3    San José          Design         2019
4  Wellington            Film         2019

In [54]:
df2.duplicated().sum()

np.int64(0)

In [55]:
df2["unesco_category"].value_counts()

unesco_category
Music                  83
Crafts and Folk Art    80
Gastronomy             66
Literature             63
Design                 53
Film                   30
Media Arts             27
Name: count, dtype: int64

3. tercer paso:  verificar datos dataset heritage y eliminar columnas.

- city
- Country (si existe)
- category (cultural, natural, mixed)
- name_en (nombre del patrimonio)

In [72]:
heritage = pd.read_csv("world_heritage.csv")
print(f"El número de filas y columnas es: {travel.shape[0]} filas y {travel.shape[1]} columnas")

El número de filas y columnas es: 560 filas y 19 columnas

In [73]:
df3 = heritage.copy()

In [65]:
def eda_basico(df3):
    print("🔍 Primeras filas del DataFrame:")
    display(df3.head())

    print("🔍 Últimas filas del DataFrame:")
    display(df3.tail())

    print("📌 Filas Aleatorias:")
    display(df3.sample(n=5))

    print("📐 Dimensiones:")
    print(f"{df3.shape[0]} filas y {df3.shape[1]} columnas\n")

    print("🧠 Información general:")
    display(df3.info())

    print("📊 Tipos de datos por columna:")
    display(df3.dtypes.rename("Tipo").to_frame())

    print("📉 Descripción de columnas numéricas:")
    display(df3.describe().T)

    print("🔤 Descripción de columnas categóricas:")
    display(df3.describe(include=["O"]))

    print("🚫 Valores nulos por columna:")
    nulos = df3.isnull().sum()
    nulos = nulos[nulos > 0].sort_values(ascending=False)
    if len(nulos) > 0:
        display(pd.DataFrame({
            "Nulos": nulos,
            "Porcentaje (%)": (nulos / len(df3) * 100).round(2)
        }))
    else:
        print("No hay valores nulos.\n")

    print("🗑️ Columnas constantes:")
    constantes = [col for col in df3.columns if df3[col].nunique() == 1]
    if constantes:
        display(pd.DataFrame({
            "Columna": constantes,
            "Valor único": [df3[col].unique()[0] for col in constantes],
            "Acción": ["Eliminar en Fase 2"] * len(constantes)
        }))
    else:
        print("No hay columnas constantes.\n")

    print("📎 Filas duplicadas:")
    dup_count = df3.duplicated().sum()
    print(f"Duplicadas: {dup_count}")
    if dup_count > 0:
        print("Ejemplo de duplicados:")
        display(df3[df3.duplicated()].head())
    else:
        print("No hay filas duplicadas.\n")

In [74]:
eda_basico(df3)

🔍 Primeras filas del DataFrame:

,unique_number,id_no,rev_bis,name_en,name_fr,name_es,name_ru,name_ar,name_zh,short_description_en,short_description_fr,short_description_es,short_description_ru,short_description_ar,short_description_zh,justification_en,justification_fr,date_inscribed,secondary_dates,danger,date_end,danger_list,longitude,latitude,area_hectares,C1,C2,C3,C4,C5,C6,N7,N8,N9,N10,criteria_txt,category,category_short,states_name_en,states_name_fr,states_name_es,states_name_ru,states_name_ar,states_name_zh,region_en,region_fr,iso_code,udnp_code,transboundary
0,230,208,Rev,Cultural Landscape and Archaeological Remains ...,Paysage culturel et vestiges archéologiques de...,Paisaje cultural y vestigios arqueológicos del...,Культурный ландшафт и археологические находки ...,المنظر الثقافي والبقايا الأثرية في وادي باميان,巴米扬山谷的文化景观和考古遗迹,<p>The cultural landscape and archaeological r...,<p>Le paysage culturel et les vestiges archéol...,<p>Este sitio es un exponente de las creacione...,<p>Культурный ландшафт и археологические наход...,"<p dir=""rtl"">يمثّل المنظر الثقافي والبقايا الأ...",<p>巴米扬山谷的文化景观和考古遗址向世人展示了从公元1世纪至13世纪期间以古代巴克特里亚文...,<p><em>Criterion (i):</em> The Buddha statues ...,<p><em>Critère (i):</em> Les statues de Bouddh...,2003,NaN,1,NaN,Y 2003,67.825250,34.846940,158.9265,1,1,1,1,0,1,0,0,0,0,(i)(ii)(iii)(iv)(vi),Cultural,C,Afghanistan,Afghanistan,Afganistán,Афганистан,أفغانستان,阿富汗,Asia and the Pacific,Asie et Pacifique,af,afg,0
1,234,211,Rev,Minaret and Archaeological Remains of Jam,Minaret et vestiges archéologiques de Djam,Minarete y vestigios arqueológicos de Jam,Минарет и археологические объекты в Джеме,مئذنة جام وبقاياها الاثرية,查姆回教寺院尖塔和考古遗址,"<p>The 65m-tall Minaret of Jam is a graceful, ...","<p>Haut de 65m, le minaret de Djam est une con...","<p>Con sus 65 metros de altura, el minarete de...",<p>65-метровый минарет Джема – грациозное и ка...,"<p dir=""rtl"">إن مئذنة جام بناء رشيق وممشوق؛ يب...",<p>65米高的查姆尖塔庄严肃穆，高耸入云，其历史可追溯到公元12世纪。塔外砌烧制精巧的砖石...,<p><em>Criterion (ii):</em> The innovative arc...,<p><em>Critère (ii)</em> : L'architecture et l...,2002,NaN,1,NaN,Y 2002,64.515889,34.396417,70.0000,0,1,1,1,0,0,0,0,0,0,(ii)(iii)(iv),Cultural,C,Afghanistan,Afghanistan,Afganistán,Афганистан,أفغانستان,阿富汗,Asia and the Pacific,Asie et Pacifique,af,afg,0
2,1590,569,Bis,Historic Centres of Berat and Gjirokastra,Centres historiques de Berat et de Gjirokastra,Ciudad Museo de Gjirokastra,Исторические центры Берата и Джирокастры,المركزان التاريخيان لبيرات وجيروكاسترا,NaN,<p>Berat and Gjirokastra are inscribed as rare...,<p>Berat et Gjirokastra sont inscrites en tant...,"<p>Situada en el valle del río Drinos, al sur ...",<p>Исторические центры Берата и Джирокастры яв...,"<p dir=""rtl"">يمثل المركزان التاريخيان لبيرات و...",NaN,NaN,NaN,2005,2008,0,NaN,NaN,20.140833,40.074167,58.9000,0,0,1,1,0,0,0,0,0,0,(iii)(iv),Cultural,C,Albania,Albanie,Albania,Албания,ألبانيا,阿尔巴尼亚,Europe and North America,Europe et Amérique du Nord,al,alb,0
3,1563,570,ter,Butrint,Butrint,Butrinto,Древний город Бутринт,بوترنت,布特林特,"<p>Inhabited since prehistoric times, Butrint ...","<p>Habité depuis les temps préhistoriques, le ...","<p>Habitado desde tiempos prehistóricos, el si...","<p>Бутринт был местом древнегреческой колонии,...","<p dir=""rtl"">إن موقع بوترنت الذي عرف استقراراً...",<p>布特林特城史前就有人定居，先后为希腊殖民地、古罗马城市和主教辖区所在地。在拜占庭时期，...,NaN,NaN,1992,1999,0,2005.0,P 1997-2005,20.020950,39.745732,NaN,0,0,1,0,0,0,0,0,0,0,(iii),Cultural,C,Albania,Albanie,Albania,Албания,ألبانيا,阿尔巴尼亚,Europe and North America,Europe et Amérique du Nord,al,alb,0
4,111,102,NaN,Al Qal'a of Beni Hammad,La Kalâa des Béni Hammad,Kalâa de los Béni-Hammad,Крепость Аль-Кала в древнем городе Бени-Хаммад,قلعة بني حمّاد,贝尼•哈玛德的卡拉城,<p>In a mountainous site of extraordinary beau...,<p>Dans un site montagneux d’une saisissante b...,<p>Situadas en un paisaje montañoso de sorpren...,<p>Расположенные в горной местности необыкнове...,"<p dir=""rtl"">ترتفع بقايا عاصمة إمارة بني حمّاد...",<p>哈玛德王朝（Hammadid emirs）第一个首都的遗址，位于风景秀美的山区，始建于...,NaN,NaN,1980,NaN,0,NaN,NaN,4.786840,35.818440,150.0000,0,0,1,0,0,0,0,0,0,0,(iii),Cultural,C,Algeria,Algérie,Argelia,Алжир,الجزائر,阿尔及利亚,Arab States,États arabes,dz,dza,0

🔍 Últimas filas del DataFrame:

,unique_number,id_no,rev_bis,name_en,name_fr,name_es,name_ru,name_ar,name_zh,short_description_en,short_description_fr,short_description_es,short_description_ru,short_description_ar,short_description_zh,justification_en,justification_fr,date_inscribed,secondary_dates,danger,date_end,danger_list,longitude,latitude,area_hectares,C1,C2,C3,C4,C5,C6,N7,N8,N9,N10,criteria_txt,category,category_short,states_name_en,states_name_fr,states_name_es,states_name_ru,states_name_ar,states_name_zh,region_en,region_fr,iso_code,udnp_code,transboundary
1243,1894,1424,NaN,Wooden <em>Tserkvas</em> of the Carpathian Reg...,<em>Tserkvas</em> en bois de la région des Car...,Tserkvas de madera de la región de los Cárpato...,NaN,NaN,NaN,<p>Situated in the eastern fringe of Central E...,<p>Situ&eacute; aux confins orientaux de l&rsq...,NaN,NaN,NaN,NaN,NaN,NaN,2013,NaN,0,NaN,NaN,21.032222,49.533889,7.030,0,0,1,1,0,0,0,0,0,0,(iii)(iv),Cultural,C,"Poland,Ukraine","Pologne,Ukraine","Polonia,Ucrania","Польша,Украина","أوكرانيا,بولندا","乌克兰,波兰",Europe and North America,Europe et Amérique du Nord,"pl,ua","pol,ukr",1
1244,1642,866,Bis,Prehistoric Rock Art Sites in the Côa Valley a...,Sites d’art rupestre préhistorique de la vallé...,Sitios de arte rupestre prehistórico del Valle...,Наскальное искусство эпохи палеолита Сиега Верде,المنطقة الأثرية للفن الصخري في سييغا فيرده,席尔加•维德（Siega Verde）岩石艺术考古区,<p>The two Prehistoric Rock Art Sites in the C...,<p>Les sites d'art rupestre préhistorique de l...,<p>Los sitios de arte rupestre prehistórico de...,<p>Включенные в Список всемирного наследия в 1...,<p>تمثل مواقع الفن الصخري ما قبل التاريخ في وا...,<p>科阿峡谷史前岩石艺术遗址于1998年列入了《世界遗产名录》，是一处集中体现旧石器时代晚...,NaN,NaN,1998,2010,0,NaN,NaN,-6.661111,40.697500,NaN,1,0,1,0,0,0,0,0,0,0,(i)(iii),Cultural,C,"Portugal,Spain","Espagne,Portugal","España,Portugal","Испания,Португалия","أسبانيا,البرتغال","葡萄牙,西班牙",Europe and North America,Europe et Amérique du Nord,"es,pt","esp,prt",1
1245,1841,1313,Rev,Heritage of Mercury. Almadén and Idrija,Patrimoine du mercure. Almadén et Idrija,Patrimonio del mercurio (Almadén e Idria),NaN,NaN,NaN,<p>The property includes the mining sites of A...,<p>Le bien inclut les sites miniers d'Almadén ...,"<p>El sitio comprende las minas de Almadén, en...",NaN,NaN,NaN,NaN,NaN,2012,NaN,0,NaN,NaN,-4.838889,38.775278,104.100,0,1,0,1,0,0,0,0,0,0,(ii)(iv),Cultural,C,"Slovenia,Spain","Espagne,Slovénie","Eslovenia,España","Испания,Словения","أسبانيا,سلوفينيا","斯洛文尼亚,西班牙",Europe and North America,Europe et Amérique du Nord,"es,si","esp,svn",1
1246,2435,1675,NaN,Silk Roads: Zarafshan-Karakum Corridor,Routes de la soie : corridor de Zeravchan-Kara...,Rutas de la seda: corredor de Zeravshan-Karakum,Шелковый путь: Зарафшан-Каракумский коридор,طرق الحرير: ممر زارافشان كاراكوم,丝绸之路：扎拉夫尚-卡拉库姆廊道,The Zarafshan-Karakum Corridor is a key sectio...,Le corridor de Zeravchan-Karakoum est un des p...,El corredor Zeravshan-Karakum es un tramo clav...,Зарафшан-Каракумский коридор — ключевой участо...,يُعتبر ممر زارافشان كاراكوم جزءاً أصيلاً من طر...,扎拉夫尚-卡拉库姆廊道是丝绸之路在中亚地区的咽喉，连接着来自各个方向的其他廊道。其全长866...,NaN,NaN,2023,NaN,0,NaN,NaN,69.685558,39.441489,669.679,0,1,1,0,1,0,0,0,0,0,(ii)(iii)(v),Cultural,C,"Tajikistan,Turkmenistan,Uzbekistan","Ouzbékistan,Tadjikistan,Turkménistan","Tayikistán,Turkmenistán,Uzbekistán","Таджикистан,Туркменистан,Узбекистан","أوزبكستان,تركمانستان,طاجيكستان","乌兹别克斯坦,土库曼斯坦,塔吉克斯坦",Asia and the Pacific,Asie et Pacifique,"tj,tm,uz","tjk,tkm,uzb",1
1247,593,509,NaN,Mosi-oa-Tunya / Victoria Falls,Mosi-oa-Tunya / Chutes Victoria,Mosi-oa-Tunya – Cataratas Victoria,Моси-оа-Тунья/Водопад Виктория,موزي أوتامبرا /شلالات فكتوريا,莫西奥图尼亚瀑布（维多利亚瀑布）,<p>These are among the most spectacular waterf...,<p>Elles figurent parmi les chutes d'eau les p...,<p>Estas cataratas figuran entre las más espec...,<p>Это один из самых великолепных водопадов ми...,"<p dir=""rtl"">تعدّ هذه الشلالات الأروع في العال...",<p>这是世界上最壮观的瀑布之一。赞比西河宽度超过2公里，瀑布奔入玄武岩峡谷，水雾形成的彩虹...,NaN,NaN,1989,NaN,0,NaN,NaN,25.855390,-17.924530,6860.000,0,0,0,0,0,0,1,1,0,0,(vii)(viii),Natural,N,"Zambia,Zimbabwe","Zambie,Zimbabwe","Zambia,Zimbabwe","Замбия,Зимбабве","زامبيا,زمبابوي","津巴布韦,赞比亚",Africa,Afrique,"zm,zw","zmb,zwe",1

📌 Filas Aleatorias:

,unique_number,id_no,rev_bis,name_en,name_fr,name_es,name_ru,name_ar,name_zh,short_description_en,short_description_fr,short_description_es,short_description_ru,short_description_ar,short_description_zh,justification_en,justification_fr,date_inscribed,secondary_dates,danger,date_end,danger_list,longitude,latitude,area_hectares,C1,C2,C3,C4,C5,C6,N7,N8,N9,N10,criteria_txt,category,category_short,states_name_en,states_name_fr,states_name_es,states_name_ru,states_name_ar,states_name_zh,region_en,region_fr,iso_code,udnp_code,transboundary
224,876,742,NaN,Historic Centre of Santa Cruz de Mompox,Centre historique de Santa Cruz de Mompox,Centro histórico de Santa Cruz de Mompox,Исторический центр города Санта-Крус-де-Момпокс,وسط سانتا كروز التاريخي في موبوكس,蒙波斯的圣克鲁斯历史中心,<p>Founded in 1540 on the banks of the River M...,<p>Fondée en 1540 sur les rives de la Magdalen...,"<p>Fundada en 1540, a orillas del rí­o Magdale...","<p>Момпокс, основанный в 1540 г. на берегах ре...","<p dir=""rtl"">تأسست مدينة موبوكس عام 1540 على ض...",<p>蒙波斯(Mompox)于1540年建立于马格达莱纳河(the River Magdal...,NaN,NaN,1995,NaN,0,NaN,NaN,-74.423084,9.240492,54.05,0,0,0,1,1,0,0,0,0,0,(iv)(v),Cultural,C,Colombia,Colombie,Colombia,Колумбия,كولومبيا,哥伦比亚,Latin America and the Caribbean,Amérique latine et Caraïbes,co,col,0
188,1169,1003,NaN,Longmen Grottoes,Grottes de Longmen,Grutas de Longmen,Пещерные храмы Лунмэнь,كهوف لونغمن,龙门石窟,<p>The grottoes and niches of Longmen contain ...,<p>Les grottes et niches de Longmen abritent l...,<p>Las grutas y nichos de Longmen albergan el ...,<p>Гроты и каменные ниши Лунмэнь содержат круп...,"<p dir=""rtl"">تأوي كهوف لونغمن المجموعة الأكبر ...",<p>龙门地区的石窟和佛龛包含北魏晚期至唐代（公元316至907年）期间最具规模和最为优秀的...,<p>Criterion (i): The sculptures of the Longme...,<p>Critère (i) : Les sculptures des grottes de...,2000,NaN,0,NaN,NaN,112.466667,34.466667,331.00,1,1,1,0,0,0,0,0,0,0,(i)(ii)(iii),Cultural,C,China,Chine,China,Китай,الصين,中国,Asia and the Pacific,Asie et Pacifique,cn,chn,0
384,1628,292,Bis,Cologne Cathedral,Cathédrale de Cologne,Catedral de Colonia,Кафедральный собор в городе Кëльн,كاثدرائية كولونيا,科隆大教堂,"<p>Begun in 1248, the construction of this Got...","<p>Commenc&eacute;e en 1248, la construction d...","<p>Iniciada en 1248, la construcci&oacute;n de...",<p>Начатое в 1248 г. строительство этого шедев...,"<p dir=""rtl"">بدأ بناء الكاتدرائية وهي تحفة من ...",<p>哥特式科隆大教堂始建于1248年，历经几个阶段的修建，直到1880才建成。在修建科隆大...,<p>The Committee decided to inscribe the nomin...,<p>Le Comit&eacute; a d&eacute;cid&eacute; d'i...,1996,NaN,0,2006.0,P 2004-2006,6.957222,50.941111,NaN,1,1,0,1,0,0,0,0,0,0,(i)(ii)(iv),Cultural,C,Germany,Allemagne,Alemania,Германия,ألمانيا,德国,Europe and North America,Europe et Amérique du Nord,de,deu,0
1124,874,740,Bis,Gough and Inaccessible Islands,Îles de Gough et Inaccessible,Islas Gough e Inaccesible,Острова Гоф и Инаксессибл (Южная Атлантика),جزيرتا غاف وايناكسيسيبل,戈夫岛和伊纳克塞瑟布尔岛,"<p>The site, located in the south Atlantic, is...",<p>Les Îles Gough et Inaccessible représentent...,"<p>Situadas al sur del Atlántico, la isla de G...",<p>Это одни из самых диких островов в пределах...,"<p dir=""rtl"">تشكل جزيرتا غاف وايناكسيسيبل جنوب...",<p>伊纳克塞瑟布尔岛位于南太平洋，面积14平方公里，是戈夫岛的扩展项目。戈夫岛于1995年...,NaN,NaN,1995,2004,0,NaN,NaN,-9.928611,-40.324722,7900.00,0,0,0,0,0,0,1,0,0,1,(vii)(x),Natural,N,United Kingdom of Great Britain and Northern I...,Royaume-Uni de Grande-Bretagne et d'Irlande du...,Reino Unido de Gran Bretaña e Irlanda del Norte,Соединенное Королевство Великобритании и Север...,المملكة المتحدة لبريطانيا العظمى وآيرلندا الشم...,大不列颠及北爱尔兰联合王国,Europe and North America,Europe et Amérique du Nord,gb,gbr,0
7,212,191,NaN,Djémila,Djémila,Yemila,Древний город Джемила,جميلة,杰米拉,"<p>Situated 900 m above sea-level, Dj&eacute;m...","<p>Dj&eacute;mila, ou Cuicul, avec son forum, ...",<p>Situada a 900 metros sobre el nivel del mar...,<p>Расположенный на высоте 900 м над уровнем м...,"<p dir=""rtl"">جميلة أو سويكول بساحتها وهياكلها ...",<p>杰米拉又叫奎库尔城 (Cuicul)，海拔900多米，城内有广场、神庙、长方形会堂、凯...,NaN,NaN,1982,NaN,0,NaN,NaN,5.736670,36.320560,30.60,0,0,1,1,0,0,0,0,0,0,(iii)(iv),Cultural,C,Algeria,Algérie,Argelia,Алжир,الجزائر,阿尔及利亚,Arab States,États arabes,dz,dza,0

📐 Dimensiones:
1248 filas y 49 columnas

🧠 Información general:
<class 'pandas.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   unique_number         1248 non-null   int64
 1   id_no                 1248 non-null   int64
 2   rev_bis               257 non-null    str
 3   name_en               1248 non-null   str
 4   name_fr               1248 non-null   str
 5   name_es               1245 non-null   str
 6   name_ru               1128 non-null   str
 7   name_ar               1141 non-null   str
 8   name_zh               1081 non-null   str
 9   short_description_en  1248 non-null   str
 10  short_description_fr  1248 non-null   str
 11  short_description_es  1223 non-null   str
 12  short_description_ru  1135 non-null   str
 13  short_description_ar  1145 non-null   str
 14  short_description_zh  1078 non-null   str
 15  justification_en      328 non-null    str
 16  justification_fr      322 non-null    str
 17  date_inscribed        1248 non-null   int64
 18  secondary_dates       95 non-null     str
 19  danger                1248 non-null   int64
 20  date_end              45 non-null     float64
 21  danger_list           94 non-null     str
 22  longitude             1247 non-null   float64
 23  latitude              1247 non-null   float64
 24  area_hectares         1226 non-null   float64
 25  C1                    1248 non-null   int64
 26  C2                    1248 non-null   int64
 27  C3                    1248 non-null   int64
 28  C4                    1248 non-null   int64
 29  C5                    1248 non-null   int64
 30  C6                    1248 non-null   int64
 31  N7                    1248 non-null   int64
 32  N8                    1248 non-null   int64
 33  N9                    1248 non-null   int64
 34  N10                   1248 non-null   int64
 35  criteria_txt          1248 non-null   str
 36  category              1248 non-null   str
 37  category_short        1248 non-null   str
 38  states_name_en        1248 non-null   str
 39  states_name_fr        1248 non-null   str
 40  states_name_es        1248 non-null   str
 41  states_name_ru        1248 non-null   str
 42  states_name_ar        1248 non-null   str
 43  states_name_zh        1248 non-null   str
 44  region_en             1248 non-null   str
 45  region_fr             1248 non-null   str
 46  iso_code              1247 non-null   str
 47  udnp_code             1247 non-null   str
 48  transboundary         1248 non-null   int64
dtypes: float64(4), int64(15), str(30)
memory usage: 477.9 KB

None

📊 Tipos de datos por columna:

                         Tipo
unique_number           int64
id_no                   int64
rev_bis                   str
name_en                   str
name_fr                   str
name_es                   str
name_ru                   str
name_ar                   str
name_zh                   str
short_description_en      str
short_description_fr      str
short_description_es      str
short_description_ru      str
short_description_ar      str
short_description_zh      str
justification_en          str
justification_fr          str
date_inscribed          int64
secondary_dates           str
danger                  int64
date_end              float64
danger_list               str
longitude             float64
latitude              float64
area_hectares         float64
C1                      int64
C2                      int64
C3                      int64
C4                      int64
C5                      int64
C6                      int64
N7                      int64
N8                      int64
N9                      int64
N10                     int64
criteria_txt              str
category                  str
category_short            str
states_name_en            str
states_name_fr            str
states_name_es            str
states_name_ru            str
states_name_ar            str
states_name_zh            str
region_en                 str
region_fr                 str
iso_code                  str
udnp_code                 str
transboundary           int64

📉 Descripción de columnas numéricas:

,count,mean,std,min,25%,50%,75%,max
unique_number,1248.0,1356.004006,7.702299e+02,4.000000,727.250000,1296.00000,2032.250000,2.666000e+03
id_no,1248.0,886.329327,5.035507e+02,1.000000,447.750000,876.50000,1333.250000,1.749000e+03
date_inscribed,1248.0,2000.424679,1.346530e+01,1978.000000,1988.750000,1999.00000,2012.000000,2.025000e+03
danger,1248.0,0.042468,2.017351e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
date_end,45.0,2009.177778,9.313453e+00,1988.000000,2004.000000,2007.00000,2017.000000,2.025000e+03
longitude,1247.0,21.561433,6.259560e+01,-179.715278,-2.994667,17.54264,51.495481,1.788345e+02
latitude,1247.0,28.864235,2.358518e+01,-54.594722,17.051623,35.86959,45.644863,7.118889e+01
area_hectares,1226.0,393456.229237,5.146754e+06,0.000000,20.650000,252.85000,14502.437500,1.662671e+08
C1,1248.0,0.211538,4.085630e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
C2,1248.0,0.386218,4.870767e-01,0.000000,0.000000,0.00000,1.000000,1.000000e+00
C3,1248.0,0.423077,4.942455e-01,0.000000,0.000000,0.00000,1.000000,1.000000e+00
C4,1248.0,0.519231,4.998303e-01,0.000000,0.000000,1.00000,1.000000,1.000000e+00
C5,1248.0,0.138622,3.456900e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
C6,1248.0,0.209936,4.074259e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
N7,1248.0,0.122596,3.281046e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
N8,1248.0,0.080128,2.716004e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
N9,1248.0,0.111378,3.147260e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
N10,1248.0,0.136218,3.431574e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00
transboundary,1248.0,0.040865,1.980577e-01,0.000000,0.000000,0.00000,0.000000,1.000000e+00

🔤 Descripción de columnas categóricas:

,rev_bis,name_en,name_fr,name_es,name_ru,name_ar,name_zh,short_description_en,short_description_fr,short_description_es,short_description_ru,short_description_ar,short_description_zh,justification_en,justification_fr,secondary_dates,danger_list,criteria_txt,category,category_short,states_name_en,states_name_fr,states_name_es,states_name_ru,states_name_ar,states_name_zh,region_en,region_fr,iso_code,udnp_code
count,257,1248,1248,1245,1128,1141,1081,1248,1248,1223,1135,1145,1078,328,322,95,94,1248,1248,1248,1248,1248,1248,1248,1248,1248,1248,1248,1247,1247
unique,11,1248,1248,1245,1126,1140,1079,1248,1248,1221,1134,1145,1077,328,322,45,68,109,3,3,212,212,212,212,212,212,7,7,211,211
top,Bis,Cultural Landscape and Archaeological Remains ...,Paysage culturel et vestiges archéologiques de...,Paisaje cultural y vestigios arqueológicos del...,Национальный парк Игуасу,مجمَّع الإقامة في شويرن,伊瓜苏国家公园,<p>The cultural landscape and archaeological r...,<p>Le paysage culturel et les vestiges archéol...,<p>Este sitio de 790.000 hectáreas posee una d...,<p>Этот исторический парковый ландшафт демонст...,"<p dir=""rtl"">يمثّل المنظر الثقافي والبقايا الأ...",<p>维琴查城于公元前2世纪修建在意大利北部，在威尼斯人的统治下，维琴查于15世纪早期到18...,<p><em>Criterion (i):</em> The Buddha statues ...,<p><em>Critère (i):</em> Les statues de Bouddh...,2010,Y 2016,(ii)(iv),Cultural,C,China,Chine,China,Китай,الصين,中国,Europe and North America,Europe et Amérique du Nord,cn,chn
freq,98,1,1,1,2,2,2,1,1,2,2,1,2,1,1,8,7,123,972,972,59,59,59,59,59,59,579,579,59,59

🚫 Valores nulos por columna:

                      Nulos  Porcentaje (%)
date_end               1203           96.39
danger_list            1154           92.47
secondary_dates        1153           92.39
rev_bis                 991           79.41
justification_fr        926           74.20
justification_en        920           73.72
short_description_zh    170           13.62
name_zh                 167           13.38
name_ru                 120            9.62
short_description_ru    113            9.05
name_ar                 107            8.57
short_description_ar    103            8.25
short_description_es     25            2.00
area_hectares            22            1.76
name_es                   3            0.24
longitude                 1            0.08
latitude                  1            0.08
iso_code                  1            0.08
udnp_code                 1            0.08

🗑️ Columnas constantes:
No hay columnas constantes.

📎 Filas duplicadas:
Duplicadas: 0
No hay filas duplicadas.

In [76]:
df3 = df3[[
        "name_en",
        "category",
        "states_name_en",
        "latitude",
        "longitude"]]

In [77]:
df3.rename(columns={
        "name_en": "heritage_name",
        "states_name_en": "country",
        "category": "heritage_category"}, inplace=True)

In [78]:
df3.head()

,heritage_name,heritage_category,country,latitude,longitude
0,Cultural Landscape and Archaeological Remains ...,Cultural,Afghanistan,34.846940,67.825250
1,Minaret and Archaeological Remains of Jam,Cultural,Afghanistan,34.396417,64.515889
2,Historic Centres of Berat and Gjirokastra,Cultural,Albania,40.074167,20.140833
3,Butrint,Cultural,Albania,39.745732,20.020950
4,Al Qal'a of Beni Hammad,Cultural,Algeria,35.818440,4.786840

In [ ]:
## Creamos tabla agregada para unir al dataset principal:

heritage_country = (df3.groupby("country").agg(heritage_sites=("heritage_name", "count")).reset_index())

In [80]:
heritage_country.head()

                                             country  heritage_sites
0                                        Afghanistan               2
1                                            Albania               2
2  Albania,Austria,Belgium,Bosnia and Herzegovina...               1
3                            Albania,North Macedonia               1
4                                            Algeria               7